import { defineManifest } from '@crxjs/vite-plugin'
import pkg from './package.json' with { type: 'json' }

const icons = {
  16: 'icons/icon-16.png',
  32: 'icons/icon-32.png',
  48: 'icons/icon-48.png',
  128: 'icons/icon-128.png',
}

export default defineManifest({
  manifest_version: 3,
  name: 'React Chrome Extension',
  short_name: 'React Ext',
  description: pkg.description,
  // Keep the extension version in lockstep with package.json so the two
  // can never drift apart the way they used to.
  version: pkg.version,
  icons,

  action: {
    default_icon: icons,
    default_title: 'Toggle the React sidebar',
    // NOTE: intentionally no `default_popup`. Declaring one would stop
    // `chrome.action.onClicked` from ever firing, which is what toggles the
    // injected sidebar. A ready-to-use popup lives in `src/popup/` — see the
    // "Using a popup instead" section of the README to switch strategies.
  },

  options_page: 'src/options/index.html',

  background: {
    service_worker: 'src/background/index.ts',
    type: 'module',
  },

  content_scripts: [
    {
      matches: ['<all_urls>'],
      js: ['src/content/index.tsx'],
      run_at: 'document_idle',
    },
  ],

  // `web_accessible_resources` is generated by CRXJS, not declared here: it
  // loads the content script as an ES module, so the module's chunks must be
  // reachable from the page. See "Known trade-offs" in the README — those URLs
  // are stable, which is a fingerprinting surface Chrome's `use_dynamic_url`
  // would close if CRXJS applied it to statically declared content scripts.

  // `activeTab` covers messaging the tab the user just clicked on, so the
  // extension does not need a broad host permission at install time.
  permissions: ['storage', 'activeTab'],
})
